### ISSUE TITLE
FATAL: Cannot find sub command for: 'esx'

### ISSUE THREAD

**Issue by laapsaap** [maintux/knife-esx#11]
I am using ruby 1.9.3 / CentOS 6.4. I succesfully installed it with gem install knife-esx  but I get FATAL: Cannot find sub command for: 'esx'.  But it still show the commands.

[root@CHANGEME SPECS]# knife esx
FATAL: Cannot find sub command for: 'esx'
Available esx subcommands: (for details, knife SUB-COMMAND --help)

*\* ESX COMMANDS **
knife esx template delete TEMPLATE_NAME [TEMPLATE_NAME](options)
knife esx template import TEMPLATE_FILE
knife esx template list
knife esx vm create (options)
knife esx vm delete VM_NAME [VM_NAME](options)
knife esx vm list (options)

[root@CHANGEME SPECS]#

**Comment by maintux** [comment]
It's correct. You have to specify which subcommand do you want to execute on esx
