### ISSUE TITLE
Create multiple NIC's on Guest

### ISSUE THREAD

**Issue by digitaljedi2** [maintux/knife-esx#12]
I'd like to be able to create multiple NIC's on an esxi guest.  I looked through the documentation, and source code but don't see a way to configure multiple interfaces.  I'm currently trying to create a guest with knife/chef/esx and up to 4 ethernet interfaces

**Comment by sethcohn** [comment]
knife esx vm create (other options)  --vm-network "Public Network - vmnic1 vmnic3, Private Network - vmnic0 vmnic2"  where those are the names of the interface ports just as they would show from the settings page, with a comma between each, and in the order eth0, eth1, etc...

**Comment by digitaljedi2** [comment]
So if I have Network adapter 1 - VM Network, Network adapter 2, VM Network, Network adapter 3, VM Network, Network adapter 4 VM Network I could simply do 

knife esx vm create --vm-name foo --use-template mytemplate.vmdk --verbose true --distro ubuntu12.04-19-gems --vm-memory 4096 -x ubuntu --vm-network "VM Network - eth0, Private Network 1 - eth1, Private Network 2 - eth2, Private Network 3, eth3, Private Network 4 - eth4"  -r role['my_role'] -i id_rsa

**Comment by sethcohn** [comment]
What goes inside the quotes as an argument to --vm-network needs to be _exactly_ whatever text would appear if you went into settings for the VM and edited the interfaces to turn them on and point them to the correct virtual interface.  Exact text matters, I suspect strongly it's just matching the correct option choice.  So in your case, if the label for the first interface _says_ 'VM Network - eth0', then yes.  If it actually says (example) 'VM network - vmnic1' then that would be what you put, and it'll become eth0.

**Comment by digitaljedi2** [comment]
Gotcha.  Thanks, worked as instructed.

**Comment by maintux** [comment]
Good! @sethcohn  thanks a lot!
