### ISSUE TITLE
Use the ESXi Embedded Host Client API instead of SSH

### ISSUE THREAD

**Issue by mrjcleaver** [maintux/knife-esx#24]
Further to https://github.com/maintux/knife-esx/issues/23 and https://github.com/chef-partners/knife-vsphere/issues/244 ESXi standalone has some sort of API that's used by ESXi Embedded Host Client. The UI is https://labs.vmware.com/flings/esxi-embedded-host-client

I'd suppose this same API could be used for knife-esx.

This would be better for people like myself that have no access to SSH on the ESXi host.

**Comment by mrjcleaver** [comment]
I've asked about API at https://labs.vmware.com/flings/esxi-embedded-host-client#comment-562593

**Comment by mrjcleaver** [comment]
So, it turns out that if you don't have SSH access you have to use the Host Client API.

_However_, that API is read-only unless you have a paid license for VMware.

Hence:

```
$ knife vsphere vm clone T6 --template T3

Cloning template T3 to new VM T6

ERROR: RbVmomi::Fault: NotSupported: The operation is not supported on the object.
```

Will fail, whereas the equivalent via knife-esx i.e. via SSH will (I assume) succeed.

**Comment by maintux** [comment]
Hi @mrjcleaver yes this gem like knife-vsphere, is a wrapper for RbVmomi. 
As you already notice, VMware allow the r/w APIs only if you have a paid license. This is the reason why I provide a flag (--free-license) that, if you have a root access to the host, uses the internal commands in place of
the APIs for the write operations.

Anyway this project is no longer developed cause I don't use VMware anymore and I don't have enough time to invest in maintenance.
